Added pre-commit hooks and updated readme.
ehn-dcc-development/eu-dcc-schema pull request #143
Opened 2022-06-08 14:11 UTC by ryanbnl

Pre-commit hooks, need to be tested (on a different machine so this is a draft for now)

2022-06-08 14:42 UTC, dslmeinte requested changes

2023-02-19 17:17 UTC, dslmeinte commented
By the looks of it, this PR mostly needs to tested out by other people than the PR creator.

2023-02-20 12:19 UTC, dslmeinte commented on hooks/pre-commit
> +# Check test cases which must be catogorized as valid
Typo: "categorized"

2023-02-20 22:18 UTC, dslmeinte commented on README.md
> +git config core.hooksPath hooks
(self-answer:) We could, but then you wouldn't be able to commit that file.

2023-02-21 11:18 UTC, ryanbnl commented
Tested with your changes and it's OK.
Because we've both committed we will need to merge ignoring the reviews - but we have both reviewed and agreed so have still followed the process.

2023-02-21 11:19 UTC, merged